import {
  Code2,
  Database,
  Server,
  Cloud,
  GitBranch,
  Shield,
  Cpu,
  Container,
  Terminal,
  Globe,
  Cog,
  Workflow,
  Layers,
  Zap,
  Lock,
  Search,
  BarChart3,
  ShoppingCart,
  Users,
  FileCode,
  Braces,
  Network,
  HardDrive,
  RefreshCw,
  Blocks,
  Webhook,
  Newspaper,
  Sparkles,
  Package,
  type LucideIcon,
} from "lucide-react";
import type { Skill, Project, Service, Experience, Certification, Testimonial, BlogPost, NavLink } from "@/types";

export const siteConfig = {
  name: "MD Jubayer Hossain",
  title: "Zend Certified PHP Engineer | Backend Developer",
  description:
    "Need a scalable Laravel backend? I am a Zend Certified PHP Engineer with 4+ years building eCommerce, marketplace & SaaS platforms. Clean architecture, measurable performance gains, and on-time delivery. Book a free consultation.",
  url: "https://jubayerhossain.com",
  ogImage: "https://jubayerhossain.com/og-image.jpg",
  author: "MD Jubayer Hossain",
  locale: "en_US",
  email: "samiulkabir9988@gmail.com",
  phone: "+8801822215188",
  whatsapp: "+8801822215188",
  linkedin: "https://www.linkedin.com/in/jubayer-hossain-936084172",
  github: "https://github.com/samiul9988",
  calendly: "https://calendly.com/jubayerhossain",
  location: "Mirpur 12, Dhaka, Bangladesh",
  yearsOfExperience: 4,
  projectsCompleted: 7,
  clientsServed: 15,
  availability: "Available for hire",
};

export const navLinks: NavLink[] = [
  { label: "Home", href: "#home" },
  { label: "About", href: "#about" },
  { label: "Skills", href: "#skills" },
  { label: "Projects", href: "#projects" },
  { label: "Services", href: "#services" },
  { label: "Experience", href: "#experience" },
  { label: "Certifications", href: "#certifications" },
  { label: "Contact", href: "#contact" },
];

export const skills: Skill[] = [
  {
    name: "PHP",
    category: "Languages",
    years: 4,
    level: 93,
    description: "Zend Certified PHP Engineer (PHP 7.4) with deep expertise in OOP, design patterns, and performance optimization.",
    icon: "Code2",
  },
  {
    name: "JavaScript",
    category: "Languages",
    years: 4,
    level: 80,
    description: "Modern ES6+ JavaScript with Node.js runtime for backend services, full-stack development, and frontend interactions.",
    icon: "FileCode",
  },
  {
    name: "TypeScript",
    category: "Languages",
    years: 2,
    level: 72,
    description: "Type-safe development with TypeScript for scalable applications, improving code reliability and developer experience.",
    icon: "FileCode",
  },
  {
    name: "SQL",
    category: "Languages",
    years: 4,
    level: 90,
    description: "Advanced SQL query optimization, complex joins, database architecture, indexing strategies, and performance tuning.",
    icon: "Database",
  },
  {
    name: "Laravel",
    category: "Frameworks",
    years: 4,
    level: 93,
    description: "Deep expertise in Laravel ecosystem — Eloquent, Queues, Events, Sanctum, package development, and enterprise application architecture.",
    icon: "Braces",
  },
  {
    name: "Node.js",
    category: "Frameworks",
    years: 3,
    level: 78,
    description: "Building backend services and APIs with Node.js, Express, real-time applications, and server-side JavaScript.",
    icon: "Server",
  },
  {
    name: "React",
    category: "Frameworks",
    years: 2,
    level: 70,
    description: "Frontend development with React.js, component-based architecture, hooks, and modern state management.",
    icon: "Cpu",
  },
  {
    name: "Yii2",
    category: "Frameworks",
    years: 3,
    level: 85,
    description: "Production-grade Yii2 applications with MongoDB integration, RBAC, and REST API development.",
    icon: "FileCode",
  },
  {
    name: "REST API",
    category: "Frameworks",
    years: 4,
    level: 92,
    description: "Designing and building scalable, secure RESTful APIs with JWT/Sanctum authentication, rate limiting, and comprehensive documentation.",
    icon: "Webhook",
  },
  {
    name: "AI / LLM Integration",
    category: "Frameworks",
    years: 1,
    level: 75,
    description: "Integrating AI and Large Language Models (Google Gemini AI, OpenAI) into Laravel applications for intelligent automation and features.",
    icon: "Sparkles",
  },
  {
    name: "Microservices",
    category: "Architecture",
    years: 2,
    level: 78,
    description: "Designing distributed systems with microservices architecture, inter-service communication, and event-driven patterns.",
    icon: "Blocks",
  },
  {
    name: "Clean Architecture",
    category: "Architecture",
    years: 3,
    level: 88,
    description: "Implementing clean architecture principles for maintainable, testable, and framework-agnostic codebases.",
    icon: "Layers",
  },
  {
    name: "SOLID Principles",
    category: "Architecture",
    years: 3,
    level: 90,
    description: "Applying SOLID principles to create flexible, maintainable, and scalable software architectures in every project.",
    icon: "Cog",
  },
  {
    name: "Repository Pattern",
    category: "Architecture",
    years: 3,
    level: 90,
    description: "Implementing repository pattern for clean data access abstraction, testability, and separation of concerns.",
    icon: "HardDrive",
  },
  {
    name: "Service Pattern",
    category: "Architecture",
    years: 3,
    level: 90,
    description: "Building service layers for business logic encapsulation, making code reusable, testable, and maintainable.",
    icon: "Workflow",
  },
  {
    name: "Event Driven",
    category: "Architecture",
    years: 2,
    level: 78,
    description: "Event-driven architecture with message brokers for scalable, loosely coupled backend systems.",
    icon: "Zap",
  },
  {
    name: "Docker",
    category: "Infrastructure",
    years: 3,
    level: 85,
    description: "Containerizing applications with Docker and Docker Compose for consistent development and production environments.",
    icon: "Container",
  },
  {
    name: "Linux",
    category: "Infrastructure",
    years: 4,
    level: 85,
    description: "Linux server administration, shell scripting, system optimization, and production deployment management.",
    icon: "Terminal",
  },
  {
    name: "Nginx",
    category: "Infrastructure",
    years: 3,
    level: 82,
    description: "Nginx configuration for reverse proxy, load balancing, caching, SSL termination, and static file serving.",
    icon: "Server",
  },
  {
    name: "Apache",
    category: "Infrastructure",
    years: 3,
    level: 80,
    description: "Apache HTTP server configuration, virtual hosts, optimization, and mod_rewrite for clean URLs.",
    icon: "Server",
  },
  {
    name: "CI/CD",
    category: "Infrastructure",
    years: 3,
    level: 82,
    description: "Continuous integration and deployment pipelines with GitHub Actions, automated testing, and streamlined deployments.",
    icon: "RefreshCw",
  },
  {
    name: "Redis",
    category: "Infrastructure",
    years: 3,
    level: 85,
    description: "Redis for caching, session management, queue handling, and real-time application performance optimization.",
    icon: "Zap",
  },
  {
    name: "RabbitMQ",
    category: "Infrastructure",
    years: 2,
    level: 72,
    description: "Message queuing with RabbitMQ for async processing, event-driven architecture, and reliable message delivery.",
    icon: "Network",
  },
  {
    name: "Meilisearch",
    category: "Infrastructure",
    years: 2,
    level: 80,
    description: "Implementing Meilisearch for high-performance, typo-tolerant full-text search and product filtering.",
    icon: "Search",
  },
  {
    name: "Cloudflare",
    category: "Infrastructure",
    years: 3,
    level: 78,
    description: "Cloudflare configuration for CDN, DNS management, SSL, DDoS protection, and web application firewall.",
    icon: "Cloud",
  },
  {
    name: "MySQL",
    category: "Databases",
    years: 4,
    level: 92,
    description: "MySQL database design, query optimization, indexing strategies, and high-performance schema architecture.",
    icon: "Database",
  },
  {
    name: "MongoDB",
    category: "Databases",
    years: 2,
    level: 78,
    description: "MongoDB schema design, aggregation pipelines, indexing, and integration with Yii2 applications.",
    icon: "Database",
  },
  {
    name: "JWT",
    category: "Authentication",
    years: 3,
    level: 88,
    description: "JSON Web Token implementation for stateless authentication, refresh tokens, and secure API access management.",
    icon: "Lock",
  },
  {
    name: "Laravel Sanctum",
    category: "Authentication",
    years: 3,
    level: 88,
    description: "Laravel Sanctum for SPA authentication, API token management, and mobile application authentication.",
    icon: "Shield",
  },
  {
    name: "Git",
    category: "Tools",
    years: 4,
    level: 90,
    description: "Advanced Git workflows, branching strategies, collaborative development, and code review processes.",
    icon: "GitBranch",
  },
  {
    name: "Queue System",
    category: "Infrastructure",
    years: 3,
    level: 85,
    description: "Job queues, background processing, failed job handling, and queue-based task scheduling for async operations.",
    icon: "Workflow",
  },
];

export const projects: Project[] = [
  {
    title: "Elegance – Enterprise B2C eCommerce Platform",
    description: "Full-stack eCommerce platform with product management, inventory, orders, coupons, payment gateways, and Meilisearch-powered product search.",
    problem: "Need for a scalable, feature-rich eCommerce solution handling product catalogs, real-time inventory, payment processing, and high-performance search for a growing B2C business.",
    solution: "Built a comprehensive Laravel backend with secure REST APIs, Redis caching, queue-based background jobs, Meilisearch for instant product search, and modular feature architecture.",
    architecture: "Modular Laravel application with Repository + Service Pattern, SOLID principles, Redis for caching and queues, MySQL for transactional data, Meilisearch for search.",
    stack: ["Laravel", "PHP", "MySQL", "Redis", "Meilisearch", "REST API", "Docker", "Vue.js"],
    challenges: [
      "Real-time inventory synchronization across product variants",
      "Complex coupon and discount engine with stacking rules",
      "High-performance product search with faceted filtering",
      "POS and inventory management integration",
    ],
    metrics: [
      { label: "API Response", value: "<100ms" },
      { label: "Search Speed", value: "<10ms" },
      { label: "Modules Built", value: "15+" },
      { label: "Architecture", value: "Clean" },
    ],
    image: "/images/project-elegance.jpg",
    demo: "https://elegance.com.bd/",
    featured: true,
  },
  {
    title: "Madhudhara – Modular Enterprise Application",
    description: "Package-based modular Laravel application with plug-and-play module installation, dynamic module management, and enterprise-grade architecture.",
    problem: "Need for a highly modular enterprise application where features can be installed, enabled, disabled, and configured independently without affecting the core system.",
    solution: "Architected a package-based Laravel application supporting dynamic module installation with RBAC, configurable permissions, and reusable service packages.",
    architecture: "Package-based modular architecture with Service Layer, Repository Pattern, SOLID principles, dynamic module management, and secure REST APIs.",
    stack: ["Laravel", "PHP", "MySQL", "REST API", "Redis", "Docker", "RBAC"],
    challenges: [
      "Designing a plug-and-play module system with zero core changes",
      "Dynamic module discovery, installation, and configuration",
      "Cross-module dependency management and communication",
      "Maintaining security isolation between modules",
    ],
    metrics: [
      { label: "Modules", value: "10+" },
      { label: "Packages", value: "5+" },
      { label: "Architecture", value: "Modular" },
      { label: "Status", value: "Production" },
    ],
    image: "/images/project-madhudhara.jpg",
    demo: "https://www.madhudhara.com/",
    featured: true,
  },
  {
    title: "AI Support Ticket System",
    description: "AI-powered customer support platform leveraging Google Gemini AI for automated response generation, intelligent ticket assistance, and workflow automation.",
    problem: "Manual customer support ticket handling causing slow response times, inconsistent replies, and high operational costs. Need for AI-assisted ticket management and automation.",
    solution: "Built a Laravel-based support platform integrating Google Gemini AI for automated response generation, smart ticket routing, and intelligent assistance for support agents.",
    architecture: "Laravel with Repository + Service Pattern, Google Gemini AI integration, secure REST APIs, RBAC, queue-based AI processing, MySQL database.",
    stack: ["Laravel", "PHP", "Gemini AI", "MySQL", "REST API", "Redis", "Docker", "RBAC"],
    challenges: [
      "Integrating AI response generation with context-aware prompts",
      "Maintaining response quality and accuracy for customer queries",
      "Designing scalable ticket management workflows",
      "Implementing role-based access for agents, admins, and customers",
    ],
    metrics: [
      { label: "Response Time", value: "<5s" },
      { label: "Automation", value: "AI-Powered" },
      { label: "RBAC Roles", value: "3" },
      { label: "Status", value: "Production" },
    ],
    image: "/images/project-ai-support.jpg",
    featured: true,
  },
  {
    title: "Telshare – Social Commerce & Marketplace",
    description: "Scalable social commerce and marketplace platform built with Yii2 and MongoDB, featuring product, brand, campaign, and business page management.",
    problem: "Need for a social commerce platform combining marketplace functionality with social features, business pages, brand management, and campaign tools.",
    solution: "Developed backend using Yii2 Framework with MongoDB for flexible schema, RESTful APIs, product and brand management, marketplace features, and business page modules.",
    architecture: "Yii2 Framework with MongoDB, modular feature architecture, RESTful API design, optimized NoSQL queries, campaign management system.",
    stack: ["Yii2", "PHP", "MongoDB", "REST API", "Git", "Linux"],
    challenges: [
      "Optimizing MongoDB queries for complex product searches",
      "Designing flexible schema for diverse product types",
      "Building campaign and marketplace management workflows",
      "Ensuring data consistency in a NoSQL environment",
    ],
    metrics: [
      { label: "Database", value: "MongoDB" },
      { label: "Modules", value: "8+" },
      { label: "Framework", value: "Yii2" },
      { label: "Status", value: "Production" },
    ],
    image: "/images/project-telshare.jpg",
    demo: "https://telshare.com/",
    featured: false,
  },
  {
    title: "DhakaWatch24 – Digital News Portal",
    description: "Complete news portal and content management system with SEO-friendly architecture, role-based access control, and media management.",
    problem: "Need for a scalable digital news portal with multi-role content management, advertisement management, SEO optimization, and high traffic handling.",
    solution: "Built a Laravel-based news CMS with RBAC for administrators, editors, and reporters, SEO-friendly URLs, sitemap generation, and optimized media handling.",
    architecture: "Laravel with RBAC, MySQL, SEO optimization layer, caching system, REST APIs for content delivery, efficient media management.",
    stack: ["Laravel", "PHP", "MySQL", "REST API", "Redis", "RBAC", "SEO"],
    challenges: [
      "Designing multi-role content approval workflows",
      "SEO-friendly URL structure and sitemap generation",
      "Handling high traffic with caching strategies",
      "Building flexible advertisement placement system",
    ],
    metrics: [
      { label: "User Roles", value: "3" },
      { label: "SEO Score", value: "95+" },
      { label: "Cache Hit", value: "90%+" },
      { label: "Framework", value: "Laravel" },
    ],
    image: "/images/project-dhakawatch.jpg",
    demo: "https://www.dhakawatch24.com/",
    featured: false,
  },
  {
    title: "SkinPlus – Scalable eCommerce Platform",
    description: "Feature-rich eCommerce platform with product catalog, inventory, order processing, customer management, and promotional campaign management.",
    problem: "Need for a scalable eCommerce backend supporting large product catalogs, complex order processing, and promotional campaigns with high performance.",
    solution: "Developed core business modules including product catalog, inventory, order processing, and campaign management with Redis caching and queue-based background jobs.",
    architecture: "Laravel with Service and Repository patterns, MySQL optimization, Redis caching, queue-based jobs, secure REST APIs, following SOLID principles.",
    stack: ["Laravel", "PHP", "MySQL", "Redis", "REST API", "REST", "SOLID"],
    challenges: [
      "Database query optimization for large product catalogs",
      "Implementing efficient promotional campaign engine",
      "Background job processing for order workflows",
      "Maintaining code quality across multiple modules",
    ],
    metrics: [
      { label: "Modules", value: "10+" },
      { label: "Query Time", value: "<80ms" },
      { label: "Cache", value: "Redis" },
      { label: "Pattern", value: "SOLID" },
    ],
    image: "/images/project-skinplus.jpg",
    demo: "https://skinplusbd.com/",
    featured: false,
  },
  {
    title: "eMartway Skincare – Collaborative eCommerce",
    description: "Large-scale collaborative eCommerce platform with real-time admin notifications via Pusher, REST APIs, and comprehensive product/order/inventory management.",
    problem: "Need for a collaborative multi-user eCommerce platform requiring real-time notifications, efficient inventory management, and scalable backend architecture.",
    solution: "Implemented real-time admin notifications using Pusher WebSockets, developed RESTful APIs, optimized database queries, and built comprehensive management modules.",
    architecture: "Laravel with Pusher WebSockets for real-time features, MySQL with query optimization, Redis caching, REST APIs, clean architecture practices.",
    stack: ["Laravel", "PHP", "MySQL", "Redis", "Pusher", "REST API", "WebSocket"],
    challenges: [
      "Real-time notification delivery with Pusher integration",
      "Collaborative workflows across multiple admin roles",
      "Database performance optimization for concurrent operations",
      "Scalable API design for mobile and web consumers",
    ],
    metrics: [
      { label: "Real-time", value: "Pusher" },
      { label: "Modules", value: "8+" },
      { label: "API Endpoints", value: "50+" },
      { label: "Status", value: "Production" },
    ],
    image: "/images/project-emartway.jpg",
    demo: "https://www.emartwayskincare.com.bd/",
    featured: false,
  },
];

export const services: Service[] = [
  {
    title: "Full-Stack Web Development",
    description: "End-to-end web application development with Laravel, Node.js, React, and TypeScript tailored to your unique business requirements.",
    icon: "Code2",
    features: ["Laravel + PHP backend", "Node.js + Express", "React frontend", "TypeScript safety", "REST & GraphQL APIs"],
  },
  {
    title: "Enterprise Laravel Development",
    description: "Enterprise-grade Laravel applications with clean architecture, modular package design, and AI/LLM integration for intelligent features.",
    icon: "Braces",
    features: ["Modular architecture", "AI / LLM integration", "Package development", "Advanced security", "Enterprise integrations"],
  },
  {
    title: "eCommerce & Marketplace",
    description: "Scalable eCommerce and marketplace platforms with product management, payment gateways, inventory, and real-time notifications via Pusher.",
    icon: "ShoppingCart",
    features: ["Product catalog", "Payment integration", "Order management", "Inventory tracking", "Multi-vendor marketplace"],
  },
  {
    title: "REST API & Microservices",
    description: "Scalable REST APIs and microservices architecture with JWT/Sanctum auth, Docker containerization, and CI/CD pipelines.",
    icon: "Webhook",
    features: ["REST API design", "Microservices", "JWT & Sanctum auth", "Rate limiting", "API documentation"],
  },
  {
    title: "DevOps & Dockerization",
    description: "Complete DevOps with Docker, CI/CD pipelines, GitHub Actions, Linux server management, Nginx, and Cloudflare CDN configuration.",
    icon: "Container",
    features: ["Docker & Compose", "CI/CD pipelines", "Nginx/Apache", "Linux admin", "Cloudflare CDN"],
  },
  {
    title: "Database & Performance",
    description: "Database architecture with MySQL, MongoDB, Redis caching, query optimization, and Meilisearch for high-performance search.",
    icon: "Database",
    features: ["MySQL / MongoDB", "Redis caching", "Query optimization", "Meilisearch", "Performance tuning"],
  },
  {
    title: "AI & LLM Integration",
    description: "Integrating Google Gemini AI, OpenAI, and LLMs into Laravel applications for automation, chatbots, and intelligent features.",
    icon: "Sparkles",
    features: ["Gemini AI", "OpenAI", "Chatbots", "Auto responses", "Smart workflows"],
  },
  {
    title: "Backend Architecture",
    description: "Architecture design using Clean Architecture, SOLID, Repository/Service patterns, Event-Driven systems, and Modular monoliths.",
    icon: "Layers",
    features: ["Clean Architecture", "SOLID principles", "Repository Pattern", "Service Layer", "Event-driven"],
  },
  {
    title: "Modernization & Refactoring",
    description: "Modernizing legacy PHP applications to Laravel, Node.js, or TypeScript with zero downtime and full knowledge transfer.",
    icon: "RefreshCw",
    features: ["Code assessment", "Laravel migration", "Node.js adoption", "Performance boost", "Knowledge transfer"],
  },
];

export const experiences: Experience[] = [
  {
    company: "Coder71 Ltd.",
    role: "Backend Developer",
    period: "Feb 2024 - Present",
    location: "Dhaka, Bangladesh",
    description: "Developing scalable Laravel applications and REST APIs for eCommerce, Marketplace, ERP, and enterprise solutions with a focus on clean architecture and performance.",
    achievements: [
      "Developed scalable Laravel applications and REST APIs for enterprise clients",
      "Built eCommerce, Marketplace, and ERP solutions handling complex business logic",
      "Implemented Redis caching, Queue systems, Payment Gateway, and Third-party API integrations",
      "Improved application performance using caching strategies, query optimization, and background jobs",
      "Worked with Docker containerization, CI/CD pipelines, Git, and Linux deployment",
    ],
    technologies: ["Laravel", "PHP", "MySQL", "Redis", "Docker", "CI/CD", "Git", "Linux", "REST API", "Meilisearch", "RabbitMQ"],
  },
  {
    company: "Dynamicflow IT",
    role: "Backend Developer",
    period: "Apr 2022 - Jan 2024",
    location: "Dhaka, Bangladesh",
    description: "Developed backend modules, designed REST APIs, optimized MySQL databases, and maintained WordPress and custom business applications for various clients.",
    achievements: [
      "Developed backend modules using Laravel and PHP for client projects",
      "Designed REST APIs and authentication systems for web and mobile applications",
      "Optimized MySQL databases and application performance through query tuning",
      "Maintained WordPress sites and custom business applications",
      "Collaborated with frontend teams to deliver end-to-end solutions",
    ],
    technologies: ["Laravel", "PHP", "MySQL", "REST API", "WordPress", "Git", "JavaScript", "Apache"],
  },
];

export const certifications: Certification[] = [
  {
    title: "Zend Certified PHP Engineer",
    issuer: "Zend Technologies (Perforce)",
    date: "PHP 7.4",
    credentialId: "ZEND032733",
    url: "https://www.zend-zce.com/en/yellow-pages/ZEND032733",
    icon: "Code2",
  },
];

export const testimonials: Testimonial[] = [
  {
    name: "Md. Asadduzzaman Arif",
    role: "IT Manager",
    company: "Apollo Hospital Dhaka",
    content: "Jubayer is a skilled backend developer with deep expertise in Laravel and PHP. His ability to architect clean, maintainable solutions and deliver on time makes him an invaluable team member. Highly recommended for complex backend projects.",
    avatar: "/images/avatar-1.jpg",
    rating: 5,
  },
  {
    name: "Abu Sayed",
    role: "Senior Software Engineer",
    company: "Coder71 Ltd.",
    content: "Jubayer consistently delivers high-quality backend solutions. His work on Elegance eCommerce platform demonstrated exceptional skills in Laravel, API design, and performance optimization. A reliable developer who takes ownership of his work.",
    avatar: "/images/avatar-2.jpg",
    rating: 5,
  },
  {
    name: "Md. Shafiqul Islam",
    role: "CEO & Lead Engineer",
    company: "Telshare Platform",
    content: "Working with Jubayer on the Telshare marketplace was a great experience. His Yii2 and MongoDB expertise, combined with clean architecture practices, resulted in a robust and scalable platform. He understands business requirements and translates them into technical solutions effectively.",
    avatar: "/images/avatar-3.jpg",
    rating: 5,
  },
];

export const blogPosts: BlogPost[] = [
  {
    title: "Building Modular Laravel Applications with Package-Based Architecture",
    description: "A deep dive into designing package-based modular Laravel applications with plug-and-play module installation, dynamic management, and enterprise-grade architecture.",
    date: "2025-06-15",
    readTime: "12 min read",
    tags: ["Laravel", "Architecture", "Packages"],
    slug: "modular-laravel-package-architecture",
    image: "/images/blog-modular.jpg",
  },
  {
    title: "Integrating Google Gemini AI with Laravel for Intelligent Applications",
    description: "Practical guide to integrating Gemini AI into Laravel applications for automated responses, intelligent ticket systems, and AI-powered features.",
    date: "2025-05-20",
    readTime: "10 min read",
    tags: ["Laravel", "AI", "Gemini"],
    slug: "gemini-ai-laravel-integration",
    image: "/images/blog-ai.jpg",
  },
  {
    title: "REST API Best Practices: From Design to Production",
    description: "Comprehensive guide covering REST API design patterns, JWT and Sanctum authentication, versioning strategies, rate limiting, and production deployment.",
    date: "2025-04-10",
    readTime: "15 min read",
    tags: ["REST API", "Laravel", "Best Practices"],
    slug: "rest-api-best-practices-laravel",
    image: "/images/blog-api.jpg",
  },
  {
    title: "Database Optimization Techniques That Actually Work",
    description: "Real-world techniques for optimizing MySQL and MongoDB queries, including indexing strategies, query restructuring, Redis caching, and performance monitoring.",
    date: "2025-03-05",
    readTime: "8 min read",
    tags: ["MySQL", "MongoDB", "Performance"],
    slug: "database-optimization-techniques",
    image: "/images/blog-database.jpg",
  },
];

export const iconMap: Record<string, LucideIcon> = {
  Code2,
  Database,
  Server,
  Cloud,
  GitBranch,
  Shield,
  Cpu,
  Container,
  Terminal,
  Globe,
  Cog,
  Workflow,
  Layers,
  Zap,
  Lock,
  Search,
  BarChart3,
  ShoppingCart,
  Users,
  FileCode,
  Braces,
  Network,
  HardDrive,
  RefreshCw,
  Blocks,
  Webhook,
  Newspaper,
  Sparkles,
  Package,
};
